name: "proxies merge"

on:
  schedule:
    - cron: '0 0/1 * * *'
  workflow_dispatch:
jobs:
  proxies_merge:
    name: merge proxies
    runs-on: ubuntu-latest

    steps:
        - name: Set time zone
          run: sudo timedatectl set-timezone 'Asia/Shanghai'
        - name: Set up Python 3.x
          uses: actions/setup-python@v2
          with:
            # Semantic version range syntax or exact version of a Python version
            python-version: '3.x'
            # Optional - x64 or x86 architecture, defaults to x64
            architecture: 'x64'
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - name: install python libs
          run: |
            pip3 install ruamel.yaml
            pip3 install requests
        - name: Checkout
          uses: actions/checkout@v2
        - name: merge proxies 
          run: python clash.py
        - name: Commit files
          run: |
              git config --local user.email "lanmoxueer@163.com"
              git config --local user.name "lanmoxueer"
              modify=`git diff HEAD`
              if [ "$modify"x != ""x ];then
                git add .
                git commit -m "`date '+%Y-%m-%d %H:%M:%S'`" #动态提交信息
                git push -u origin main && echo "Git Pushed Origin"
              fi
        - name: Mirror the Github organization repos to Gitee.
          uses: Yikun/hub-mirror-action@v1.1
          with:
            src: github/lanmoxueer
            dst: gitee/goldplan
            dst_key: ${{ secrets.GITEE_RSA }}
            dst_token: ${{ secrets.GITEE_TOKEN }}
            white_list: "proxies_merge"
            clone_style: "ssh"
            debug: true
